# -*- coding: utf-8 -*-
"""Asistensi 17-18 - Python Feb23

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zrHAMcCwq4ylBkVJ7GOWgN2miB8KCnyH

# $\text{Python Feb 22 | Asistensi 17 - 18 | Mini Case}$

#Mini Case - NaekBis
Terdapa sebuah perusahaan bis yang ingin menerapakan digitalisai pada proses bisisnya. 
Pada rencana digitalisai ini salah satu program yang diajukan adalah Sistem scan-in scan-out pada bus. 
Setiap penumpang yang naik atau turun bis akan menggunakan smartphonenya untuk melakukan scan.
Jadi setiap penumpang naik akan melakukan scan-in dan saat turun akan melakukan scan-out. 
Pada saat scan-in data penumpang akan disimpan untuk melakuakn perhitungan biaya pada saat turun.
Pada saat scan-out akan disampaikan jumlah kilometer perjalanan dan biaya yang perlu dibayarkan, bis akan menyimpan total pendapatan yang telah dihasilkannya.

Data penumpang yang perlu disimpan:
* Nama
* Jenis Kelamin
* KM masuk bis

Bis akan menyimpan beberapa informasi:
* kapasitas_penumpang
* kilometer_perjalanan
* biaya_per_km

Bis akan memiliki fungsi:
* scan_in
* scan_out
* pendapatan
* perjalanan

jika diperlukan, silahkan tambahkan informasi atau fungsi yang mungkin dibutuhkan untuk menyelesaikan kasus di atas
"""


# main.py

"""---
# $\text{Feedback Asistensi}$
Terima Kasih telah mengikuti sesi asistensi hari ini! 😀

Jangan lupa untuk mengisi feedback juga yaa, link feedback dapat diakses di
[sini](https://bit.ly/FeedbackAsistensiSDE-Feb23)
- Kelas = Python
- Teaching Assistant = Muhamad Sepryan Astrayesa
- Pekan = 7
"""